# basics of python

In [119]:
print('alex')


alex


In [120]:
x=5
print(f"the value of x is {x}")

the value of x is 5


In [121]:
if x>10:
    print('bigger')
else:
    print('smaller')

smaller


### python qutation

In [122]:
'it\'s good thing'

"it's good thing"

In [123]:
"it's good thing"

"it's good thing"

In [124]:

x='hello world'
x[5:1]

''

### first task
### find the next square value

In [125]:
import math
def next_seq(x):
    
    if x>0:
       y=math.sqrt(x)
      
       y=int(y)
       y+=1
       x=y**(2)
    else:
        x=-1
    print(x)  
x=input('enter x:')
x=int(x)
next_seq(x)


enter x: 4


9


### the second task
### find the unique value in the list

In [126]:
x=[1,2,2,3,2,3,2]
x.count(2)
len(x)

7

In [127]:
def find_unique(x):
    for i,v in enumerate(x):
     z=x.count(x[i])
     if z==1:
       return x[i]
            
x=[1,1,1,1,1,1,5]
y=find_unique(x)
print(y)
        

5


### the third task
### filter the list from the none intger value

In [128]:
numbers = [1, 2, 3]
result = isinstance(numbers, list)
print(result) # Output: True

True


In [129]:
y=[]
for i,v in enumerate(x):
    if isinstance(x[i], int):
        y.append(x[i]) 

    

In [130]:
def list_filter(x):
    y=[]
    for i,v in enumerate(x):
       if isinstance(x[i], int):
          y.append(x[i])
    return y      

x=[1,'a',5,'k',3]
z=list_filter(x)
print(z)
    


[1, 5, 3]


In [131]:
x=[1,2,'a','d',4,6]
[i for i in x if isinstance(i, int)]

[1, 2, 4, 6]

### the fourth task
### count the number of vowel character in the string

In [132]:
def vowel_count(x):
    x=x.lower()
    count=0
    for i in x:
        if(i=='a' or i=='e' or i=='i' or i=='o' or i=='u'):
           count+=1
    return count
x='hEEllo world'
z=vowel_count(x)
print(z)

4


In [133]:
def vowel_count(x):
    x=x.lower()
    count=0
    for i in x:
        if i in ['a','e','i','o','u']:
           count+=1
    return count
x='hEEllo world'
z=vowel_count(x)
print(z)

4


### the fifth task
### enumeration example

In [134]:
x=[1,'debi','hello',[8,7,6],(5,7,9)]
for i,v in enumerate(x):
    print(i)
    print(v)

0
1
1
debi
2
hello
3
[8, 7, 6]
4
(5, 7, 9)


# numpy

## basics

In [135]:
import numpy as np

In [136]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [137]:
arr.dtype

dtype('int32')

In [138]:
type(arr)

numpy.ndarray

In [139]:
arr.shape

(3,)

In [140]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [141]:
arr.size

3

In [142]:
arr.sum()

6

In [143]:
arr.max()

3

In [144]:
np.min(arr)

1

In [145]:
np.mean(arr)

2.0

In [146]:
np.median(arr)

2.0

In [147]:
np.var(arr)

0.6666666666666666

In [148]:
np.std(arr)

0.816496580927726

In [149]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [150]:
np.max(arr,axis=0)

array([7, 8, 9])

In [151]:
np.max(arr,axis=1)

array([3, 6, 9])

In [152]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [153]:
np.argmax(arr)

8

In [154]:
np.argmax(arr, axis=1)

array([2, 2, 2], dtype=int64)

#### broadcasting 
##### operation for item level

In [155]:
arr+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [156]:
arr*5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [157]:
arr=arr+2
arr

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

##### operation for row level

In [159]:
arr+np.array([4,5,6]) ## add for row

array([[ 7,  9, 11],
       [10, 12, 14],
       [13, 15, 17]])

In [160]:
arr@np.array([1,2,3]) ## dot product

array([26, 44, 62])

In [163]:
np.matmul(np.array([2,3]),np.array([[2],[3]]))  ## matrix multplication

array([13])

##### access the item in matrix

In [167]:
a=np.array([[1,2,3,4,5],
            [6,7,8,9,10]])
a[0,2]

3

In [168]:
a[1,2]

8

In [170]:
a[:,2]

array([3, 8])

#### reshape

In [171]:
arr=np.array([1,2,3,4])
arr.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [172]:
arr=np.array([1,2,3,4,8,9,6,10])
arr.reshape(2,-1)

array([[ 1,  2,  3,  4],
       [ 8,  9,  6, 10]])

In [173]:
arr=np.array([1,2,3,4,8,9,6,10])
arr.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 8,  9],
       [ 6, 10]])

#### create matrix

In [181]:
np.eye(5) ## an identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [176]:
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [179]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [182]:
np.full((2, 2), 6.3) ## constant matrix

array([[6.3, 6.3],
       [6.3, 6.3]])

# Regex
#### regular expression

In [183]:
import re

In [ ]:
re.search()

In [184]:
txt='the rain in spain'
x=re.search('ai',txt)
print(x)
print(x.group()) ## the pattern
print(x.span())  ## refer to the first time that this pattern occure

<re.Match object; span=(5, 7), match='ai'>
ai
(5, 7)


In [ ]:
re.findall()

In [185]:
x=re.findall('ai',txt) ## get all times that the pattern happen but without the place
print(x)

['ai', 'ai']


In [188]:
txt='Saturday and Sunday are weekends'
re.findall(r'sat|sun|mon',txt,re.IGNORECASE) ## or txt.lower

['Sat', 'Sun']

In [189]:
txt='hello world'
re.findall(r'[a-zA-Z]',txt)

['h', 'e', 'l', 'l', 'o', 'w', 'o', 'r', 'l', 'd']

In [190]:
txt='hello world33'
re.findall(r'[a-zA-Z0-9]',txt)

['h', 'e', 'l', 'l', 'o', 'w', 'o', 'r', 'l', 'd', '3', '3']

In [191]:
txt='hello ,world.33'
re.findall(r'[a-zA-Z0-9,.]',txt)

['h', 'e', 'l', 'l', 'o', ',', 'w', 'o', 'r', 'l', 'd', '.', '3', '3']

In [192]:
txt='cat can concrete'
re.findall(r'c..',txt)

['cat', 'can', 'con', 'cre']

In [196]:
re.findall(r'\bc\w{2}\b',txt)

['cat', 'can']

In [198]:
re.findall(r'\b\w{3,8}\b',txt)

['cat', 'can', 'concrete']

In [199]:
re.findall(r'\d{3}','test 123456899')

['123', '456', '899']

In [202]:
re.findall(r'^[A-Z]','Hello\nworld\nPython')

['H']

In [203]:
re.findall(r'^[A-Z]','Hello\nworld\nPython',re.MULTILINE)

['H', 'P']

In [208]:
re.findall(r'd+$','Line 1\n Line \n Line 3',re.MULTILINE)

[]